name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test-and-Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2.4.0
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      - name: Install and Build
        run: |
          npm install
          npm run build
